### ISSUE TITLE
怎么在goland里配置debug方式运行cmd/ginadmin/main.go

### ISSUE THREAD

**Issue by xiu2020** [gphper/ginadmin#13]
你好，

怎么在goland里配置debug方式运行cmd/ginadmin/main.go？ 这样方便断点调试，谢谢

**Comment by gphper** [comment]
[文档](https://gphper.github.io/ginadmindoc/#/start)
![捕获](https://user-images.githubusercontent.com/18718299/211311769-ac32a9ce-1cfc-492d-a033-a8a6f2d4e9c1.PNG)

**Comment by xiu2020** [comment]
非常感谢~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gphper/ginadmin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月9日(星期一) 晚上8:50
***@***.***&gt;;
抄送:&nbsp;"shi ***@***.******@***.***&gt;;
主题:&nbsp;Re: [gphper/ginadmin] 怎么在goland里配置debug方式运行cmd/ginadmin/main.go (Issue #13)





 
文档
