### ISSUE TITLE
请问如何部署到线上呢

### ISSUE THREAD

**Issue by nobody05** [gphper/ginadmin#18]
线上部署
使用 go build .\cmd\ginadmin 生成二进制文件
打包静态资源部署 go build -tags=embed .\cmd\ginadmin

按照这个说明，生成两个二进制文件，然后应该怎么在线上操作呢

**Comment by gphper** [comment]
`go build .\cmd\ginadmin` 这种你需要把静态资源文件一起上传到服务器上
`go build -tags=embed .\cmd\ginadmin` 这种就只部署一个编译好的二进制文件就行了，因为静态资源打包进去了
