### ISSUE TITLE
执行报错【./main.go:26:45: syntax error: unexpected run, expecting comma or )】

### ISSUE THREAD

**Issue by lyyyann** [gphper/ginadmin#2]
报错如图，是我哪里没有配置好吗？
![image](https://i.postimg.cc/j5c5YL2y/2021-06-08-8-26-41.png)

**Comment by gphper** [comment]
仔细看下 **templatesDgo_run_ir**  这变量从哪来的

**Comment by lyyyann** [comment]
你的代码，我一个字都没有改动，编译时报错。请教一下，这个应该如何处理呢？

**Comment by lyyyann** [comment]
> 仔细看下 **templatesDgo_run_ir** 这变量从哪来的

你的代码，我一个字都没有改动，编译时报错。请教一下，这个应该如何处理呢？

**Comment by gphper** [comment]
可能是你无意间改的， 把26行的 templatesDgo_run_ir 改成 templatesDir 就行了

**Comment by lyyyann** [comment]
> 可能是你无意间改的， 把26行的 templatesDgo_run_ir 改成 templatesDir 就行了

多谢大神，我刚才对了一下github上的源码，确实如您所说，可能是ide格式化时候的问题吧。
问题了解决了，非常感谢，多谢您的热心及时的答复！
