### ISSUE TITLE
考虑加入单元测试吗？

### ISSUE THREAD

**Issue by LemonLzy** [gphper/ginadmin#5]
拜读了大部分代码，发现没有单元测试，也想学习下单元测试的具体应用

**Comment by gphper** [comment]
我记得开始是写了单元测试的，但是只写了公共方法的单元测试，有时间再加上吧。开发中觉得单元测试最大的好处就是写完一个方法后，不需要再去到main.go 文件中修改代码来测试新写的方法了，取而代之的是写个单元测试加 -v 直接运行一下就能看到效果了，而且后期想升级这个方法的时候运行一个原先的测试用例来判断新写的方法是否兼容原来的逻辑。至于后台管理的那些controller 方法，我觉得没必要加单元测试，反正都要在浏览器里面运行查看效果。但是提供给前端的api接口还是要加单元测试的，gin框架的http单元测试，网上很多教程的，个人见解仅供参考，哈哈
